import { Step } from 'react-joyride';

export const useJoyrideSteps = (
  templateType: string,
): Step[] => {
  const mainPipelineSteps: Step[] = [
    {
      target: '#nav-start-pipeline',
      title: 'Start Pipeline',
      content: 'Click here to begin setting up a new pipeline.',
      placement: 'right',
      disableBeacon: true,
      spotlightClicks: false,
    },
    {
      target: '.pipeline-start-1',
      title: 'Pipeline Templates',
      content: 'These are the available pipeline templates.',
      placement: 'top',
      spotlightClicks: false,
    },
    {
      target: '.sia-start-button',
      title: 'Start SIA Pipeline using a Template',
      content: 'Click "Next" to open this template.',
      placement: 'right',
      spotlightClicks: false,
    },
    {
      target: `.react-flow__node-datasourceNode[data-id="0"]`,
      title: 'Datasource Node',
      content: 'Start by configuring your datasource.',
      placement: 'top',
      spotlightClicks: false,
    },
    {
      target: '#datasource-modal',
      title: 'Datasource Modal',
      content: 'This is where you configure your datasource.',
      placement: 'right',
      spotlightClicks: false,
    },
    {
      target: '#datasource-dropdown',
      title: 'Datasource Dropdown',
      content: 'Click to select a datasource.',
      placement: 'top',
      spotlightClicks: true,
    },
    {
      target: '#datasource-dropdown .dropdown-menu.show',
      title: 'Select a Datasource',
      content: 'Now select a datasource from the list.',
      placement: 'top',
      spotlightClicks: true,
    },
    {
      target: '#file-browser-container',
      title: 'Choose Media Folder',
      content: 'Upload files using the upload box above, then browse and select the folder as input.',
      placement: 'top',
      spotlightClicks: true,
    },
    {
      target: '#selected-datasource-path',
      title: 'Selected Path',
      content: 'Here is the path you selected.',
      placement: 'bottom',
      spotlightClicks: false,
    },
    {
      target: '#done-button',
      title: 'Done',
      content: 'Click "Done" to finalize your Datasource configuration.',
      placement: 'bottom',
      spotlightClicks: true,
    },
    {
      target: `.react-flow__node.script-node`,
      title: 'Script Node',
      content: 'This script is already configured. Click "Next" to continue.',
      placement: 'top',
      spotlightClicks: false,
      disableBeacon: true,
    },
    {
      target: `.react-flow__node.anno-task-node`,
      title: 'Annotation Node',
      content: 'Click to configure the annotation task.',
      placement: 'top',
      spotlightClicks: false,
      disableBeacon: true,
    },
    {
      target: '#name',
      title: 'Annotation Task Name',
      content: 'Give your annotation task a clear and descriptive name.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#instruction',
      title: 'Instructions (Optional)',
      content: 'Optionally, provide instructions to help annotators understand the task.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.step1next',
      title: 'Continue to Next Step',
      content: 'Click "Next" to continue after filling out task details.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#userSelect',
      title: 'User or Group Selection',
      content: 'Select a user or group to assign this annotation task.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.step2next',
      title: 'Continue to Next Step',
      content: 'Click "Next" to continue after selecting the user.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#treeSelect',
      title: 'Label Tree Selection',
      content: 'Select a label tree to categorize your annotations. You will be able to select labels in the next step.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.step3next',
      title: 'Continue to Next Step',
      content: 'Click "Next" to continue after selecting the label tree.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#select-label-container',
      title: 'Label Selection',
      content:
        'Select one or more labels to include in your annotation task. You can activate entire branches by clicking parent nodes.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.step4next',
      title: 'Continue',
      content: 'Click "Next" after selecting your labels.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#select-storage-container',
      title: 'Dataset Selection',
      content:
        'Choose a dataset where the annotations for this task will be stored. You can also create a new one if needed.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.step5next',
      title: 'Continue to Next Step',
      content: 'Click "Next" to continue after selecting or creating a dataset.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#sia-configuration-heading',
      content: 'This section lets you configure SIA annotation tools and actions.',
      disableBeacon: true,
      placement: 'right',
      spotlightClicks: true,
    },
    {
      target: '.steplast',
      content: 'Click this button to finish the configuration process.',
      disableBeacon: true,
      placement: 'top',
      spotlightClicks: true,
    },
    {
      target: '.step-template-next',
      title: 'Next Step',
      content: 'Click this "Next" button to proceed to the next step of configuring your pipeline template.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.start-pipeline-modal',
      title: 'Pipeline Name',
      content: 'Enter a name for your pipeline so you can identify it later.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '#description',
      title: 'Pipeline Description',
      content: 'Optionally add a description to remember the purpose of this pipeline.',
      placement: 'right',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.start-pipeline-btn',
      title: 'Launch Your Pipeline',
      content: 'Click here to start your configured pipeline.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.latest-pipeline-row',
      title: 'Latest Created Pipeline',
      content: 'This is the pipeline created. Click "Next" to continue Annotation.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    },
    {
      target: '.first-row-class',
      title: 'Latest Annotation Task',
      content: 'This is your most recently created annotation task.',
      placement: 'top',
      spotlightClicks: true,
      disableBeacon: true,
    }
  ];

  if (templateType === 'mainPipeline') {
    return mainPipelineSteps;
  }

  if (templateType === 'miaPipeline') {
    const miaPipelineSteps: Step[] = [
      {
        target: '#nav-start-pipeline',
        title: 'Start Pipeline',
        content: 'Click here to begin setting up a new pipeline.',
        placement: 'right',
        disableBeacon: true,
        spotlightClicks: false,
      },
      {
        target: '.pipeline-start-1',
        title: 'Pipeline Templates',
        content: 'These are the available pipeline templates.',
        placement: 'top',
        spotlightClicks: false,
      },
      {
        target: '.mia-start-button',
        title: 'Start MIA Pipeline using a Template',
        content: 'Click "Next" to open this template.',
        placement: 'right',
        spotlightClicks: false,
      },
      {
        target: `.react-flow__node-datasourceNode[data-id="0"]`,
        title: 'Datasource Node',
        content: 'Start by configuring your datasource node for MIA pipeline.',
        placement: 'top',
        spotlightClicks: false,
      },
      {
        target: '#datasource-modal',
        title: 'Datasource Modal',
        content: 'This is where you configure your datasource.',
        placement: 'right',
        spotlightClicks: false,
      },
      {
        target: '#datasource-dropdown',
        title: 'Datasource Dropdown',
        content: 'Click to select a datasource.',
        placement: 'top',
        spotlightClicks: true,
      },
      {
        target: '#datasource-dropdown .dropdown-menu.show',
        title: 'Select a Datasource',
        content: 'Now select a datasource from the list.',
        placement: 'top',
        spotlightClicks: true,
      },
      {
        target: '#file-browser-container',
        title: 'Choose Media Folder',
        content: 'Upload files using the upload box above, then browse and select the folder as input.',
        placement: 'top',
        spotlightClicks: true,
      },
      {
        target: '#selected-datasource-path',
        title: 'Selected Path',
        content: 'Here is the path you selected.',
        placement: 'bottom',
        spotlightClicks: false,
      },
      {
        target: '#done-button',
        title: 'Done',
        content: 'Click "Done" to finalize your Datasource configuration.',
        placement: 'bottom',
        spotlightClicks: true,
      },
      {
        target: `.react-flow__node.script-node`,
        title: 'Script Node',
        content: 'This script is already configured. Click "Next" to continue.',
        placement: 'top',
        spotlightClicks: false,
        disableBeacon: true,
      },
      {
        target: `.react-flow__node.anno-task-node`,
        title: 'Annotation Task Node',
        content: 'Click to configure your annotation task for MIA pipeline.',
        placement: 'top',
        spotlightClicks: false,
        disableBeacon: true,
      },
      {
        target: '#name',
        title: 'Annotation Task Name',
        content: 'Provide a descriptive name for your annotation task.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#instruction',
        title: 'Instructions (Optional)',
        content: 'Optionally, provide instructions for annotators.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.step1next',
        title: 'Continue to Next Step',
        content: 'Click "Next" to continue after filling out task details.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#userSelect',
        title: 'User or Group Selection',
        content: 'Assign a user or group to this annotation task.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.step2next',
        title: 'Continue to Next Step',
        content: 'Click "Next" to continue after selecting the user.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#treeSelect',
        title: 'Label Tree Selection',
        content: 'Select a label tree to categorize annotations.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.step3next',
        title: 'Continue to Next Step',
        content: 'Click "Next" after selecting the label tree.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#select-label-container',
        title: 'Label Selection',
        content:
          'Select one or more labels for the annotation task.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.step4next',
        title: 'Continue',
        content: 'Click "Next" after selecting your labels.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#select-storage-container',
        title: 'Dataset Selection',
        content: 'Choose or create a dataset to store annotations.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.step5next',
        title: 'Continue to Next Step',
        content: 'Click "Next" to continue after selecting or creating a dataset.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#mia-configuration-heading',
        content: 'Configure MIA-specific annotation tools and actions here.',
        disableBeacon: true,
        placement: 'right',
        spotlightClicks: true,
      },
      {
        target: '.steplast',
        content: 'Click this button to finish the configuration process.',
        disableBeacon: true,
        placement: 'top',
        spotlightClicks: true,
      },
      {
        target: '.step-template-next',
        title: 'Next Step',
        content: 'Click this "Next" button to proceed with your MIA pipeline template.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.start-pipeline-modal',
        title: 'Pipeline Name',
        content: 'Enter a name for your MIA pipeline.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '#description',
        title: 'Pipeline Description',
        content: 'Optionally add a description for your pipeline.',
        placement: 'right',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.start-pipeline-btn',
        title: 'Launch Your Pipeline',
        content: 'Click here to start your configured MIA pipeline.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.latest-pipeline-row',
        title: 'Latest Created Pipeline',
        content: 'This is the pipeline you created. The pipeline execution is being initialized and might take a few seconds. Please wait before clicking "Next" to continue to Annotation.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      },
      {
        target: '.first-row-class',
        title: 'Latest Annotation Task',
        content: 'This is your most recently created annotation task for the pipeline.',
        placement: 'top',
        spotlightClicks: true,
        disableBeacon: true,
      }
    ];

    return miaPipelineSteps;
  }

  return [];
};