export const pipelineStepMap = {
  'skip-navigate': 1,
  'highlight-ds-node': 3,
  'dropdown-open': 6,
  'datasource-selected': 7,
  'path-selected': 8,
  'done-clicked': 10,
  'anno-name': 11,
  'anno-task-info-done': 15,
  'user-selection-done': 17,
  'label-tree-selection-done': 19,
  'label-selection-done': 21,
  'storage-settings-done': 23,
  'configuration-done': 25,
  'template-next': 26,
  'latest-running-pipeline': 29,
  'latest-running-annotask': 30,
};

export const instructionStepMap = {
  'start-instruction': 0,
  'add-step-clicked': 2,
  'open-file-browser': 5,
  'save-step': 6,
  'instruction-list': 7,
  'last-row-highlight': 8,
  'edit-step': 10,
  'save-step2': 11,
  'pipelines-nav': 12,
  'after-nav': 14,
  'dropdown-open': 19,
  'datasource-selected': 20,
  'path-selected': 21,
  'done-clicked': 23,
  'anno-name': 24,
  'anno-task-info-done': 28,
  'user-selection-done': 30,
  'label-tree-selection-done': 32,
  'label-selection-done': 34,
  'storage-settings-done': 36,
  'configuration-done': 38,
  'template-next': 39,
  'anno-task-display': 42,
  'view-created-pipeline': 43,
  'view-created-annotask': 44,
};

export const instructionStepMap2 = {
  'start-instruction': 0,
  'add-step-clicked': 2,
  'open-file-browser': 5,
  'save-step': 6,
  'instruction-list': 7,
  'last-row-highlight': 8,
  'edit-step': 10,
  'save-step2': 11,
  'pipelines-nav': 12,
  'after-nav': 14,
  'view-created-pipeline': 15,
  'view-created-annotask': 16,
};

export const labelStepMap = {
  'latest-label-tree': 4,
};