export const pipelineStepMap = {
  'skip-navigate': 1,
  'navigate-to-template': 2,
  'highlight-ds-node': 3,
  'navigate-to-dsnode': 4,
  'dropdown-open': 6,
  'datasource-selected': 7,
  'path-selected': 8,
  'done-clicked': 10,
  'anno-name': 11,
  'navigate-to-annoTasknode': 12,
  'anno-task-info-done': 15,
  'user-selection-done': 17,
  'label-tree-selection-done': 19,
  'label-selection-done': 21,
  'storage-settings-done': 23,
  'configuration-done': 25,
  'template-next': 26,
  'latest-running-pipeline': 29,
  'latest-running-annotask': 30,
}

export const instructionStepMap = {
  'start-instruction': 0,
  'add-step-clicked': 2,
  'open-file-browser': 5,
  'insert-button-active': 6,
  'save-step': 7,
  'instruction-list': 8,
  'last-row-highlight': 9,
  'edit-step': 11,
  'save-step2': 12,
  'pipelines-nav': 13,
  'after-nav': 15,
  'dropdown-open': 20,
  'datasource-selected': 21,
  'path-selected': 22,
  'done-clicked': 24,
  'anno-name': 25,
  'anno-task-info-done': 29,
  'user-selection-done': 31,
  'label-tree-selection-done': 33,
  'label-selection-done': 35,
  'storage-settings-done': 37,
  'configuration-done': 39,
  'template-next': 40,
  'anno-task-display': 43,
  'view-created-pipeline': 44,
  'view-created-annotask': 45,
}

export const instructionStepMap2 = {
  'start-instruction': 0,
  'add-step-clicked': 2,
  'open-file-browser': 5,
  'insert-button-active': 6,
  'save-step': 7,
  'instruction-list': 8,
  'last-row-highlight': 9,
  'edit-step': 11,
  'save-step2': 12,
  'pipelines-nav': 13,
  'after-nav': 15,
  'view-created-pipeline': 16,
  'view-created-annotask': 17,
}

export const labelStepMap = {
  'skip-tocreate': 1,
  'latest-label-tree': 4,
  'open-edit-modal': 5,
  'create-label': 7,
}
