export const GET_MIA_ANNOS = 'GET_MIA_ANNOS'
export const GET_MIA_IMAGE = 'GET_MIA_IMAGE'
export const MIA_ZOOM = 'MIA_ZOOM'
export const MIA_AMOUNT = 'MIA_AMOUNT'
export const MIA_TOGGLE_ACTIVE = 'MIA_TOGGLE_ACTIVE'
export const GET_MIA_LABEL = 'GET_MIA_LABEL'
export const MIA_SELECT_LABEL = 'MIA_SELECT_LABEL'