export const SIA_REVIEW_SET_ELEMENT = 'SIA_REVIEW_SET_ELEMENT'
export const SIA_REVIEW_SET_OPTIONS = 'SIA_REVIEW_SET_OPTIONS'
export const SIA_REVIEW_SET_ANNOS = 'SIA_REVIEW_SET_ANNOS'
export const SIA_REVIEW_RESET_ANNOS = 'SIA_REVIEW_RESET_ANNOS'