export const ANNO_DELETED='annoDeleted'
export const ANNO_SELECTED='annoSselected'
export const ANNO_CREATED='annoCreated'
export const ANNO_MOVED='annoMoved'
export const ANNO_EDITED='annoEdited'
export const ANNO_ADDED_NODE='annoAddedNode'
export const ANNO_LABEL_UPDATE='annoLabelUpdate'
export const ANNO_CREATED_NODE='annoCreatedNode'
export const ANNO_CREATED_FINAL_NODE='annoCreatedFinalNode'
export const ANNO_START_CREATING='annoStartCreating'

