export const VIEW='view'
export const EDIT='edit'
export const CREATE='create'
export const MOVE='move'
export const ADD = 'add'
export const CAMERA_MOVE = 'cameraMove'
export const EDIT_LABEL = 'editLabel'
export const DELETED = 'deleted'