//Anno actions
export const ANNO_DELETED='annoDeleted'
export const ANNO_SELECTED='annoSselected'
export const ANNO_CREATED='annoCreated'
export const ANNO_MOVED='annoMoved'
export const ANNO_ENTER_MOVE_MODE='annoEnterMoveMode'
export const ANNO_EDITED='annoEdited'
export const ANNO_ENTER_EDIT_MODE='annoEnterEditMode'
export const ANNO_ADDED_NODE='annoAddedNode'
export const ANNO_REMOVED_NODE='annoRemovedNode'
export const ANNO_LABEL_UPDATE='annoLabelUpdate'
export const ANNO_CREATED_NODE='annoCreatedNode'
export const ANNO_CREATED_FINAL_NODE='annoCreatedFinalNode'
export const ANNO_START_CREATING='annoStartCreating'
export const ANNO_COMMENT_UPDATE='annoCommentUpdate'
export const ANNO_MARK_EXAMPLE='annoMarkExample'
export const ANNO_ENTER_CREATE_MODE='annoEnterCreateMode'

export const CANVAS_SVG_UPDATE='canvasSvgUpdate'
export const CANVAS_UI_CONFIG_UPDATE='canvasUiConfigUpdate'
export const CANVAS_AUTO_SAVE='canvasAutoSave'
export const CANVAS_LABEL_INPUT_CLOSE='canvasLabelInputClose'
export const CANVAS_IMG_LOADED='canvasImgLoaded'
export const CANVAS_IMGBAR_CLOSE='canvasImgbarClose'

//Image actions
export const IMG_LABEL_UPDATE='imgLabelUpdate'
export const IMG_JUNK_UPDATE='imgJunkUpdate'
export const IMG_ANNO_TIME_UPDATE='imgAnnoTimeUpdate'