export const AUTH_USER = 'auth_user'
export const AUTH_ERR = 'auth_err'
export const DECODE_JWT = 'decode_jwt'
export const CHANGE_VIEW = 'change_view'
export const LOGOUT = 'logout'
export const SET_NAVBAR_VISIBLE = 'SET_NAVBAR_VISIBLE'
export const LOGIN_STATUS = 'LOGIN_STATUS'
export const SET_SETTINGS = 'SET_SETTINGS'