python3 import_pipe_project.py '../api/examples/pipes/anno_all_imgs'
python3 import_pipe_project.py '../api/examples/pipes/export_annos'
python3 import_pipe_project.py '../api/examples/pipes/loop'
python3 import_pipe_project.py '../api/examples/pipes/pipe_context'
python3 import_pipe_project.py '../api/examples/pipes/sia'
python3 import_pipe_project.py '../api/examples/pipes/two_stage_anno'
python3 import_pipe_project.py '../api/examples/pipes/vis_args'