import "./wizard.scss"

import { NodeTemplate } from "l3p-core"

const DEFAULT_PARAMS = { 
    title: "no title",
    icon: "fa fa-heart",
    content: `
        <h4>no content</h4>    
    `,
}

/**
 * @param icon: css class
 * @param title: a title
 * @param content: template string 
 */
export default class WizardTab {
    constructor(params: any){
        params = Object.assign({}, DEFAULT_PARAMS, params)
        const { title, icon, content } = params

        // validate icon string
        if(icon === undefined || typeof(icon) !== "string"){
            throw new Error("use an icon string.")
        }
        this.icon = icon
        
        // the data-targt or href will be generated by 'Wizard'
        this.nav = new NodeTemplate(`
            <li>
                <a data-ref="a">
                    <span class="round-tab">
                        <i class="${icon}"></i>
                    </span>
                </a>
            </li>
        `)

        // the id will be generated by 'Wizard'
        this.pane = new NodeTemplate(`
            <div class="tab-pane">
                ${(title !== undefined) 
                    ? `<h3>${title}</h3>`
                    : ``
                }
                ${content}
            </div>
        `)
        this.html = this.pane
    }

    enable(){
        this.nav.root.classList.toggle("disabled", false)
    }
    disable(){
        this.nav.root.classList.toggle("disabled", true)
    }

    /**
     * @todo: if this method is called manually it wont work properly.
     * there u cant deactivate the previous activated tab from here.
     * hence dont use this method (how to hide it?) 
     * use the click event instead.
     * @todo: maybe add typecheck function? bstprctis?
     * @param {*} hook 
     */
    activate(){
        this.nav.root.classList.toggle("disabled", false)
        this.nav.root.classList.toggle("active", true)
        this.pane.root.classList.toggle("disabled", false)
        this.pane.root.classList.toggle("active", true)
    } 
    deactivate(){
        this.nav.root.classList.toggle("active", false)
        this.pane.root.classList.toggle("disabled", true)
        this.pane.root.classList.toggle("active", false)
    }
}
